apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-pipeline-sa # Make sure this matches the Role name bound to your SA
  namespace: argo
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch