apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-pipeline-sa
  namespace: argo
---
# Permissions inside the 'argo' namespace to manage its own testing lifecycle
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-pod-orchestrator
  namespace: argo
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-pod-orchestrator-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: demo-pipeline-sa
    namespace: argo
roleRef:
  kind: Role
  name: workflow-pod-orchestrator
  apiGroup: rbac.authorization.k8s.io
---
# Permissions inside the 'demo-testing' namespace ONLY to track app readiness
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-app-checker
  namespace: demo-testing
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-app-checker-binding
  namespace: demo-testing
subjects:
  - kind: ServiceAccount
    name: demo-pipeline-sa
    namespace: argo
roleRef:
  kind: Role
  name: workflow-app-checker
  apiGroup: rbac.authorization.k8s.io